controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fl_extending_arm_joint_controller:
      type: position_controllers/JointGroupPositionController

# Position Controllers ---------------------------------------
fl_extending_arm_joint_controller:
  ros__parameters:
    joints:
      - fl_extending_arm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity