vel_driver:
  ros__parameters:
    # subscribing topic names
    control_cmd_vel_topic: /cmd_vel
    extention_length_topic: /extending_in_meter_controller
    # publishing topic names
    front_left_steer_cmd_topic: /fwids/front_left_steer_rad/command
    front_right_steer_cmd_topic: /fwids/front_right_steer_rad/command
    rear_left_steer_cmd_topic: /fwids/rear_left_steer_rad/command
    rear_right_steer_cmd_topic: /fwids/rear_right_steer_rad/command
    front_left_rotor_cmd_topic: /fwids/front_left_rotor_radpersec/command
    front_right_rotor_cmd_topic: /fwids/front_right_rotor_radpersec/command
    rear_left_rotor_cmd_topic: /fwids/rear_left_rotor_radpersec/command
    rear_right_rotor_cmd_topic: /fwids/rear_right_rotor_radpersec/command

    # vehicle parameters
    l_f: 0.607 # front axle to center of mass [m]
    l_r: 0.607 # rear axle to center of mass [m]
    d_l: 0.405 # left wheel to center of mass [m]
    d_r: 0.405 # right wheel to center of mass [m]
    tire_radius: 0.1 # wheel radius [m]
